// Minimal JS placeholder for future interactivity
// Highlights the current page in the navigation menu 
// generated by cursor but it has a bug, two index.html will be both highlighted
document.addEventListener('DOMContentLoaded', () => {
  const here = location.pathname.split('/').pop() || 'index.html';
  document.querySelectorAll('nav a').forEach(a => {
    const href = a.getAttribute('href');
    if (href && href.endsWith(here)) a.style.fontWeight = '700';
  });
});

